name: Run

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: 'main'
  repository_dispatch:
    types: [run-workflow]
  schedule:
    - cron:  '23 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event_name == 'schedule' && 'main' || github.event.inputs.branch }}
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}   
