name: Run

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: 'main'
  repository_dispatch:
    types: [run-workflow]
  schedule:
    - cron:  '20 8 * * *'

jobs:
  build:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
